<?php
require_once dirname(__DIR__).'/includes/bootstrap.php';
require_once dirname(__DIR__).'/includes/admin.php';
admin_session_start();
$pdo=db();
$page=isset($_GET['page'])?preg_replace('/[^a-z_]/','',$_GET['page']):'dashboard';
$allowed=['dashboard','sections','services','gallery','content','theme','navigation','settings','testimonials','bookings','account','activity','media'];
if(!in_array($page,$allowed,true))$page='dashboard';
if(isset($_GET['logout'])){admin_logout();header('Location: index.php');exit;}
$error='';$notice='';
if(!admin_logged_in()){
  if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['login'])){
    admin_csrf_check();
    $username=trim($_POST['username']??'');$password=$_POST['password']??'';
    $stmt=$pdo->prepare("SELECT * FROM admin_users WHERE username=? AND is_active=1 LIMIT 1");$stmt->execute([$username]);$user=$stmt->fetch();
    if($user && (!empty($user['locked_until']) && strtotime($user['locked_until'])>time())){$error='Too many failed attempts. Please try again later.';}
    elseif($user && password_verify($password,$user['password_hash'])){
      session_regenerate_id(true);$_SESSION['wave_admin_id']=$user['id'];$_SESSION['wave_admin_name']=$user['display_name'];
      $pdo->prepare("UPDATE admin_users SET failed_attempts=0,locked_until=NULL,last_login_at=NOW() WHERE id=?")->execute([$user['id']]);
      admin_log('login','Administrator signed in');header('Location: index.php');exit;
    }else{
      if($user){$fails=(int)$user['failed_attempts']+1;$lock=$fails>=5?date('Y-m-d H:i:s',time()+900):null;$pdo->prepare("UPDATE admin_users SET failed_attempts=?,locked_until=? WHERE id=?")->execute([$fails,$lock,$user['id']]);}
      $error='Invalid username or password.';
    }
  }
  ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login | Wave Photography</title><link rel="stylesheet" href="admin.css"></head><body class="login-body"><main class="login-card"><div class="login-logo"><img src="../assets/logo/wave-photography-primary.png" alt="Wave Photography"></div><span class="eyebrow">SECURE ADMINISTRATION</span><h1>Welcome back</h1><p>Sign in to manage your photography website.</p><?php if($error):?><div class="alert error"><?=admin_h($error)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><label>Username<input name="username" autocomplete="username" required autofocus></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="btn primary full" name="login" value="1">Sign in to dashboard</button></form><a class="back-link" href="../index.php">← Back to website</a></main></body></html><?php
  exit;
}
$adminId=(int)$_SESSION['wave_admin_id'];
function postv($k,$d=''){return trim((string)($_POST[$k]??$d));}
function redirect_page($p){header('Location: index.php?page='.rawurlencode($p));exit;}
function upload_image($field,$existing=''){
  if(empty($_FILES[$field]) || $_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return $existing;
  $f=$_FILES[$field];if($f['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Image upload failed. Please try again.');
  if($f['size']>8*1024*1024)throw new RuntimeException('Each image must be smaller than 8 MB.');
  $finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($f['tmp_name']);
  $types=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
  if(!isset($types[$mime]))throw new RuntimeException('Only JPG, PNG and WebP images are supported.');
  $dir=dirname(__DIR__).'/uploads/media';if(!is_dir($dir) && !mkdir($dir,0755,true))throw new RuntimeException('Upload directory could not be created.');
  $name=bin2hex(random_bytes(16)).'.'.$types[$mime];
  if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Could not save uploaded image. Check folder permissions.');
  $relative='uploads/media/'.$name;
  try{$q=db()->prepare("INSERT INTO media_library(original_name,stored_name,file_path,mime_type,file_size,uploaded_by) VALUES(?,?,?,?,?,?)");$q->execute([substr($f['name'],0,255),$name,$relative,$mime,(int)$f['size'],!empty($_SESSION['wave_admin_id'])?(int)$_SESSION['wave_admin_id']:null]);}catch(Throwable $e){error_log('[Wave media library] '.$e->getMessage());}
  return $relative;
}
function make_thumbnail($relative){
 $source=dirname(__DIR__).'/'.$relative;if(!extension_loaded('gd')||!is_file($source))return $relative;
 $info=@getimagesize($source);if(!$info||empty($info['mime']))return $relative;
 $loaders=['image/jpeg'=>'imagecreatefromjpeg','image/png'=>'imagecreatefrompng','image/webp'=>'imagecreatefromwebp'];
 $loader=$loaders[$info['mime']]??null;if(!$loader||!function_exists($loader))return $relative;
 $src=@$loader($source);if(!$src)return $relative;
 $w=imagesx($src);$h=imagesy($src);$max=720;$scale=min(1,$max/max($w,$h));$nw=max(1,(int)round($w*$scale));$nh=max(1,(int)round($h*$scale));
 $dst=imagecreatetruecolor($nw,$nh);imagealphablending($dst,false);imagesavealpha($dst,true);
 $transparent=imagecolorallocatealpha($dst,0,0,0,127);imagefilledrectangle($dst,0,0,$nw,$nh,$transparent);
 imagecopyresampled($dst,$src,0,0,0,0,$nw,$nh,$w,$h);
 $dir=dirname($source).'/thumbs';if(!is_dir($dir))@mkdir($dir,0755,true);
 $name=pathinfo($source,PATHINFO_FILENAME).'-thumb.webp';$target=$dir.'/'.$name;
 $ok=function_exists('imagewebp')?imagewebp($dst,$target,82):false;
 imagedestroy($src);imagedestroy($dst);
 return $ok?'uploads/media/thumbs/'.$name:$relative;
}
function slugify_admin($s){$s=strtolower(trim($s));$s=preg_replace('/[^a-z0-9]+/','-',$s);return trim($s,'-')?:('section-'.time());}
try{
if($_SERVER['REQUEST_METHOD']==='POST' && !isset($_POST['login'])){
 admin_csrf_check();$action=postv('action');
 if($action==='save_section'){
  $id=(int)($_POST['id']??0);$name=postv('name');$cat=postv('category',$name);$slug=slugify_admin(postv('slug',$name));$desc=postv('description');$image=upload_image('cover_image',postv('existing_image'));
  if(!$name)throw new RuntimeException('Section name is required.');
  if($id){$q=$pdo->prepare("UPDATE website_sections SET name=?,slug=?,category=?,description=?,cover_image=?,layout=?,sort_order=?,is_active=? WHERE id=?");$q->execute([$name,$slug,$cat,$desc,$image,postv('layout','gallery'),(int)postv('sort_order'),isset($_POST['is_active'])?1:0,$id]);}
  else{$q=$pdo->prepare("INSERT INTO website_sections(name,slug,category,description,cover_image,layout,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?)");$q->execute([$name,$slug,$cat,$desc,$image,postv('layout','gallery'),(int)postv('sort_order'),isset($_POST['is_active'])?1:0]);}
  $defaultImage=$image?:'assets/gallery/sample-14.svg';
  $pdo->prepare("INSERT INTO services(slug,name,category,image,description,sort_order,is_active) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),category=VALUES(category),image=VALUES(image),description=VALUES(description),sort_order=VALUES(sort_order),is_active=VALUES(is_active)")->execute([$slug,$name,$cat,$defaultImage,$desc,(int)postv('sort_order'),isset($_POST['is_active'])?1:0]);
  admin_log('section_saved',$name);redirect_page('sections');
 }
 if($action==='delete_section'){$id=(int)$_POST['id'];$q=$pdo->prepare("SELECT category FROM website_sections WHERE id=?");$q->execute([$id]);$cat=$q->fetchColumn();if($cat){$pdo->prepare("UPDATE portfolio_photos SET is_active=0 WHERE category=?")->execute([$cat]);$pdo->prepare("UPDATE website_sections SET is_active=0,deleted_at=NOW() WHERE id=?")->execute([$id]);$pdo->prepare("UPDATE services SET is_active=0 WHERE category=?")->execute([$cat]);admin_log('section_archived',$cat);}redirect_page('sections');}
 if($action==='save_service'){
  $id=(int)($_POST['id']??0);$name=postv('name');$slug=slugify_admin(postv('slug',$name));$cat=postv('category',$name);$img=upload_image('image_file',postv('image'));$desc=postv('description');$inc=array_values(array_filter(array_map('trim',explode("\n",postv('inclusions')))));
  if(!$name||!$img)throw new RuntimeException('Service name and service image are required.');
  if($id)$pdo->prepare("UPDATE services SET name=?,slug=?,category=?,image=?,description=?,inclusions=?,sort_order=?,is_active=? WHERE id=?")->execute([$name,$slug,$cat,$img,$desc,json_encode($inc), (int)postv('sort_order'),isset($_POST['is_active'])?1:0,$id]);
  else $pdo->prepare("INSERT INTO services(name,slug,category,image,description,inclusions,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?)")->execute([$name,$slug,$cat,$img,$desc,json_encode($inc),(int)postv('sort_order'),isset($_POST['is_active'])?1:0]);
  $pdo->prepare("INSERT INTO website_sections(name,slug,category,description,cover_image,sort_order,is_active) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),cover_image=VALUES(cover_image),is_active=VALUES(is_active)")->execute([$name,$slug,$cat,$desc,$img,(int)postv('sort_order'),isset($_POST['is_active'])?1:0]);
  admin_log('service_saved',$name);redirect_page('services');
 }
 if($action==='delete_service'){$id=(int)$_POST['id'];$pdo->prepare("UPDATE services SET is_active=0 WHERE id=?")->execute([$id]);redirect_page('services');}
 if($action==='bulk_upload'){
  $cat=postv('category');$files=$_FILES['image_files']??null;if(!$cat||!$files)throw new RuntimeException('Choose a section and at least one image.');
  $added=0;
  foreach(($files['name']??[]) as $i=>$original){
   if(($files['error'][$i]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)continue;
   $_FILES['bulk_one']=['name'=>$files['name'][$i],'type'=>$files['type'][$i],'tmp_name'=>$files['tmp_name'][$i],'error'=>$files['error'][$i],'size'=>$files['size'][$i]];
   $path=upload_image('bulk_one','');$thumb=make_thumbnail($path);$title=pathinfo($original,PATHINFO_FILENAME);
   $pdo->prepare("INSERT INTO portfolio_photos(title,category,image,thumbnail,featured,is_placeholder,sort_order,is_active) VALUES(?,?,?,?,0,0,?,1)")->execute([$title,$cat,$path,$thumb,(int)postv('sort_order')+$added]);$added++;
  }
  if(!$added)throw new RuntimeException('No valid images were uploaded.');
  admin_log('gallery_bulk_upload',$added.' images uploaded');redirect_page('gallery');
 }
 if($action==='save_photo'){
  $id=(int)($_POST['id']??0);$title=postv('title');$cat=postv('category');$img=upload_image('image_file',postv('image'));$thumb=make_thumbnail($img);if(!$title||!$cat||!$img)throw new RuntimeException('Title, category and image are required.');
  if($id)$pdo->prepare("UPDATE portfolio_photos SET title=?,category=?,image=?,thumbnail=?,featured=?,is_active=?,caption=?,alt_text=?,sort_order=?,is_cover=? WHERE id=?")->execute([$title,$cat,$img,$thumb,isset($_POST['featured'])?1:0,isset($_POST['is_active'])?1:0,postv('caption'),postv('alt_text'),(int)postv('sort_order'),isset($_POST['is_cover'])?1:0,$id]);
  else $pdo->prepare("INSERT INTO portfolio_photos(title,category,image,thumbnail,featured,is_placeholder,sort_order,is_active) VALUES(?,?,?,?,?,0,?,1)")->execute([$title,$cat,$img,$thumb,isset($_POST['featured'])?1:0,(int)postv('sort_order')]);
  admin_log('photo_saved',$title);redirect_page('gallery');
 }
 if($action==='delete_photo'){$pdo->prepare("UPDATE portfolio_photos SET is_active=0 WHERE id=?")->execute([(int)$_POST['id']]);redirect_page('gallery');}
 if($action==='save_content'){foreach(($_POST['content']??[]) as $k=>$v){$pdo->prepare("INSERT INTO website_content(content_key,content_value) VALUES(?,?) ON DUPLICATE KEY UPDATE content_value=VALUES(content_value)")->execute([$k,trim($v)]);}foreach(['hero_image_file'=>'hero_image','about_image_file'=>'about_image'] as $f=>$k){$path=upload_image($f,'');if($path)$pdo->prepare("INSERT INTO website_content(content_key,content_value,content_type) VALUES(?,?,?) ON DUPLICATE KEY UPDATE content_value=VALUES(content_value),content_type=VALUES(content_type)")->execute([$k,$path,'image']);}admin_log('content_updated','Website copy and media updated');redirect_page('content');}
 if($action==='reset_theme'){$defaults=['primary_color'=>'#0b6f82','secondary_color'=>'#1c5664','accent_color'=>'#20b99a','page_background'=>'#f5fbfa','section_background'=>'#ffffff','card_background'=>'#ffffff','header_background'=>'#1c5664','footer_background'=>'#073b49','heading_color'=>'#123342','text_color'=>'#344f59','nav_text_color'=>'#ffffff','button_background'=>'#20b99a','button_text_color'=>'#073b49','font_family'=>'Inter','container_width'=>'1200','section_spacing'=>'80','border_radius'=>'18'];foreach($defaults as $k=>$v)$pdo->prepare("INSERT INTO theme_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")->execute([$k,$v]);admin_log('theme_reset','Theme restored to defaults');redirect_page('theme');}
 if($action==='save_theme'){$colors=['primary_color','secondary_color','accent_color','page_background','section_background','card_background','header_background','footer_background','heading_color','text_color','nav_text_color','button_background','button_text_color'];$fonts=['Inter','Arial','Georgia','Poppins','Roboto','Montserrat'];foreach(($_POST['theme']??[]) as $k=>$v){$v=trim($v);if(in_array($k,$colors,true)&&!preg_match('/^#[0-9a-fA-F]{6}$/',$v))continue;if($k==='font_family'&&!in_array($v,$fonts,true))continue;if(in_array($k,['container_width','section_spacing','border_radius'],true))$v=(string)max(0,min(2400,(int)$v));if(!in_array($k,$colors,true)&&!in_array($k,$fonts,true)&&!in_array($k,['font_family','container_width','section_spacing','border_radius'],true))continue;$pdo->prepare("INSERT INTO theme_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")->execute([$k,$v]);}admin_log('theme_updated','Theme configuration updated');redirect_page('theme');}
 if($action==='save_navigation'){$id=(int)($_POST['id']??0);$url=postv('url');if(!preg_match('~^(https?://|/|#|[a-zA-Z0-9_-])~',$url)||(preg_match('~^[a-z][a-z0-9+.-]*:~i',$url)&&!preg_match('~^https?://~i',$url)))throw new RuntimeException('Enter a valid internal path or http/https URL.');$v=[postv('label'),$url,(int)postv('sort_order'),isset($_POST['open_new_tab'])?1:0,isset($_POST['is_active'])?1:0];if($id)$pdo->prepare("UPDATE navigation_items SET label=?,url=?,sort_order=?,open_new_tab=?,is_active=? WHERE id=?")->execute(array_merge($v,[$id]));else $pdo->prepare("INSERT INTO navigation_items(label,url,sort_order,open_new_tab,is_active) VALUES(?,?,?,?,?)")->execute($v);admin_log('navigation_saved',$v[0]);redirect_page('navigation');}
 if($action==='delete_navigation'){$pdo->prepare("DELETE FROM navigation_items WHERE id=?")->execute([(int)$_POST['id']]);redirect_page('navigation');}
 if($action==='save_settings'){foreach(($_POST['settings']??[]) as $k=>$v){$v=trim($v);if(in_array($k,['instagram','facebook','youtube','google_maps_url'],true)&&$v!==''&&(!filter_var($v,FILTER_VALIDATE_URL)||!in_array(parse_url($v,PHP_URL_SCHEME),['http','https'],true)))throw new RuntimeException('Social and map links must be valid http/https URLs.');if($k==='whatsapp')$v=preg_replace('/[^0-9]/','',$v);$pdo->prepare("INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")->execute([$k,$v]);}foreach(['logo_file'=>'logo','favicon_file'=>'favicon'] as $fieldName=>$key){$path=upload_image($fieldName,'');if($path)$pdo->prepare("INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")->execute([$key,$path]);}admin_log('settings_updated','Global website settings updated');redirect_page('settings');}
 if($action==='save_testimonial'){$id=(int)($_POST['id']??0);$vals=[postv('customer_name'),postv('category'),postv('review'),isset($_POST['is_active'])?1:0];if($id)$pdo->prepare("UPDATE testimonials SET customer_name=?,category=?,review=?,is_active=? WHERE id=?")->execute(array_merge($vals,[$id]));else $pdo->prepare("INSERT INTO testimonials(customer_name,category,review,is_active,is_sample) VALUES(?,?,?,?,0)")->execute($vals);redirect_page('testimonials');}
 if($action==='delete_testimonial'){$pdo->prepare("UPDATE testimonials SET is_active=0 WHERE id=?")->execute([(int)$_POST['id']]);redirect_page('testimonials');}
 if($action==='booking_status'){$pdo->prepare("UPDATE bookings SET status=? WHERE id=?")->execute([postv('status'),(int)$_POST['id']]);redirect_page('bookings');}
 if($action==='change_password'){$u=$pdo->prepare("SELECT password_hash FROM admin_users WHERE id=?");$u->execute([$adminId]);$hash=$u->fetchColumn();if(!password_verify(postv('current_password'),$hash))throw new RuntimeException('Current password is incorrect.');if(strlen(postv('new_password'))<10)throw new RuntimeException('New password must contain at least 10 characters.');$pdo->prepare("UPDATE admin_users SET password_hash=? WHERE id=?")->execute([password_hash(postv('new_password'),PASSWORD_DEFAULT),$adminId]);admin_log('password_changed','Administrator password changed');$notice='Password updated.';}
}
}catch(Throwable $e){$error=$e->getMessage();error_log('[Wave Admin] '.$e->getMessage());}
function count_table($table){$allowed=['services','portfolio_photos','testimonials','bookings','website_sections','website_content','media_library'];if(!in_array($table,$allowed,true))return 0;return (int)db()->query("SELECT COUNT(*) FROM `$table`".(in_array($table,['services','portfolio_photos','testimonials','website_sections'])?' WHERE is_active=1':''))->fetchColumn();}
function admin_form_start($action){echo '<form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="csrf" value="'.admin_h(admin_csrf()).'"><input type="hidden" name="action" value="'.admin_h($action).'">';}
function field($label,$name,$value='',$type='text',$extra=''){echo '<label>'.admin_h($label).'<input type="'.admin_h($type).'" name="'.admin_h($name).'" value="'.admin_h($value).'" '.$extra.'></label>';}
function textarea_field($label,$name,$value=''){echo '<label>'.admin_h($label).'<textarea name="'.admin_h($name).'" rows="4">'.admin_h($value).'</textarea></label>';}
function rows($sql){return db()->query($sql)->fetchAll();}
$stats=['Sections'=>count_table('website_sections'),'Images'=>count_table('portfolio_photos'),'Uploaded media'=>count_table('media_library'),'Services'=>count_table('services'),'Testimonials'=>count_table('testimonials'),'Content blocks'=>count_table('website_content')];
$labels=['dashboard'=>'Dashboard','sections'=>'Sections','gallery'=>'Gallery','services'=>'Services','content'=>'Website content','navigation'=>'Navigation','theme'=>'Theme','settings'=>'Settings','testimonials'=>'Testimonials','bookings'=>'Bookings','account'=>'Admin account','activity'=>'Activity log','media'=>'Media library'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=admin_h($labels[$page])?> | Wave Admin</title><link rel="stylesheet" href="admin.css"></head><body class="admin-body"><div class="admin-shell"><aside class="sidebar" id="sidebar"><a class="side-brand" href="../index.php"><img src="../assets/logo/wave-photography-primary.png" alt="Wave Photography"></a><div class="side-label">WORKSPACE</div><?php foreach($labels as $k=>$v):?><a class="side-link <?=$page===$k?'active':''?>" href="?page=<?=$k?>"><span><?=admin_h($v)?></span></a><?php endforeach;?><a class="side-link" href="../index.php" target="_blank">View website ↗</a><a class="side-link logout" href="?logout=1">Sign out</a></aside><main class="admin-main"><header class="topbar"><button class="mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('show')">☰</button><div><small>WAVE PHOTOGRAPHY / ADMIN</small><h1><?=admin_h($labels[$page])?></h1></div><div class="top-user"><span class="avatar">A</span><span><?=admin_h($_SESSION['wave_admin_name'])?></span></div></header><div class="content-area"><?php if($error):?><div class="alert error"><?=admin_h($error)?></div><?php endif;?><?php if($notice):?><div class="alert success"><?=admin_h($notice)?></div><?php endif;?>
<?php if($page==='dashboard'):?><div class="welcome"><div><span class="eyebrow">OVERVIEW</span><h2>Your website, one place.</h2><p>Manage your photography website and keep every story up to date.</p></div><a class="btn primary" href="../index.php" target="_blank">Preview website ↗</a></div><div class="stats"><?php foreach($stats as $k=>$v):?><div class="stat-card"><span><?=admin_h($k)?></span><strong><?=$v?></strong><small>Live database records</small></div><?php endforeach;?></div><div class="panel"><div class="panel-head"><div><h3>Quick actions</h3><p>Common website management tasks</p></div></div><div class="quick-grid"><?php foreach(['sections'=>'Add new section','gallery'=>'Upload photographs','services'=>'Manage services','content'=>'Edit website content','theme'=>'Customize theme','navigation'=>'Manage navigation','settings'=>'Website settings','bookings'=>'View enquiries'] as $k=>$v):?><a class="quick-card" href="?page=<?=$k?>"><b>＋</b><span><?=admin_h($v)?></span><i>→</i></a><?php endforeach;?></div></div><div class="panel"><div class="panel-head"><div><h3>Recent activity</h3><p>Latest changes made in this portal</p></div><a href="?page=activity">View all</a></div><?php $logs=rows("SELECT action,details,created_at FROM admin_activity_logs ORDER BY id DESC LIMIT 6");if(!$logs):?><p class="muted">No activity recorded yet.</p><?php else:foreach($logs as $l):?><div class="activity-row"><b><?=admin_h(str_replace('_',' ',$l['action']))?></b><span><?=admin_h($l['details'])?></span><time><?=admin_h($l['created_at'])?></time></div><?php endforeach;endif;?></div>
<?php elseif($page==='sections'):?><div class="panel" id="section-editor"><div class="panel-head"><div><h3>Create or edit a photography section</h3><p>New sections automatically become available as gallery categories.</p></div></div><?php admin_form_start('save_section');?><input type="hidden" name="id" value=""><input type="hidden" name="existing_image" value=""><div class="form-grid"><?php field('Section name','name');field('URL slug (optional)','slug');field('Gallery category','category');field('Display order','sort_order','0','number');?><label>Cover image<input type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"></label><label>Layout<select name="layout"><option value="gallery">Gallery</option><option value="masonry">Masonry</option><option value="grid">Grid</option></select></label></div><?php textarea_field('Description','description');?><label class="check"><input type="checkbox" name="is_active" checked> Publish this section</label><button class="btn primary">Save section</button></form></div><div class="panel"><h3>Existing sections</h3><?php foreach(rows("SELECT * FROM website_sections WHERE deleted_at IS NULL ORDER BY sort_order,id") as $r):?><div class="manage-row"><div><b><?=admin_h($r['name'])?></b><small><?=admin_h($r['category'])?> · <?= $r['is_active']?'Published':'Hidden'?></small></div><span><?=admin_h($r['description'])?></span><button type="button" class="btn small" data-edit-section="<?=admin_h(json_encode($r))?>">Edit</button><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="delete_section"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger small" onclick="return confirm('Hide this section and its gallery images?')">Delete</button></form></div><?php endforeach;?></div>
<?php elseif($page==='services'):?><div class="panel" id="service-editor"><div class="panel-head"><div><h3>Add or update a service</h3><p>Service changes are reflected on the public website.</p></div></div><?php admin_form_start('save_service');?><input type="hidden" name="id" value=""><input type="hidden" name="image" value=""><div class="form-grid"><?php field('Service name','name');field('Slug (optional)','slug');field('Gallery category','category');field('Display order','sort_order','0','number');?><label>Service image<input type="file" name="image_file" accept="image/jpeg,image/png,image/webp"></label></div><?php textarea_field('Description','description');textarea_field('What is included (one item per line)','inclusions');?><label class="check"><input type="checkbox" name="is_active" checked> Active on website</label><button class="btn primary">Save service</button></form></div><div class="panel"><h3>Current services</h3><?php foreach(rows("SELECT * FROM services ORDER BY sort_order,id") as $r):?><div class="manage-row"><img class="thumb" src="../<?=admin_h($r['image'])?>" alt=""><div><b><?=admin_h($r['name'])?></b><small><?=admin_h($r['category'])?> · <?=$r['is_active']?'Active':'Hidden'?></small></div><span><?=admin_h($r['description'])?></span><button type="button" class="btn small" data-edit-service="<?=admin_h(json_encode($r))?>">Edit</button><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="delete_service"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger small" onclick="return confirm('Hide this service?')">Hide</button></form></div><?php endforeach;?></div>
<?php elseif($page==='gallery'):?><div class="panel"><h3>Upload a photograph</h3><p class="muted">JPG, PNG and WebP · maximum 8 MB per image. Uploads are stored in the website media library.</p><?php admin_form_start('bulk_upload');?><div class="form-grid"><label>Section / category<select name="category" required><?php foreach(rows("SELECT DISTINCT category FROM website_sections WHERE is_active=1 ORDER BY sort_order") as $c):?><option><?=admin_h($c['category'])?></option><?php endforeach;?></select></label><label>Photographs<input type="file" name="image_files[]" accept="image/jpeg,image/png,image/webp" multiple required></label><?php field('Display order','sort_order','0','number');?></div><button class="btn primary">Upload photograph</button></form></div><div class="photo-grid"><?php foreach(rows("SELECT * FROM portfolio_photos WHERE is_active=1 ORDER BY sort_order,id DESC") as $r):?><article class="photo-card"><img src="../<?=admin_h($r['image'])?>" alt="<?=admin_h($r['title'])?>"><div><b><?=admin_h($r['title'])?></b><small><?=admin_h($r['category'])?> <?=$r['featured']?'· Featured':''?></small><details><summary>Edit details / replace image</summary><?php admin_form_start('save_photo');?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="image" value="<?=admin_h($r['image'])?>"><?php field('Title','title',$r['title']);?><label>Category<select name="category"><?php foreach(rows("SELECT DISTINCT category FROM website_sections WHERE is_active=1 ORDER BY sort_order") as $c):?><option <?= $c['category']===$r['category']?'selected':''?>><?=admin_h($c['category'])?></option><?php endforeach;?></select></label><?php field('Caption','caption',$r['caption']??'');field('Alt text','alt_text',$r['alt_text']??'');field('Display order','sort_order',$r['sort_order'],'number');?><label class="check"><input type="checkbox" name="is_cover" <?=$r['is_cover']?'checked':''?>> Use as section cover</label><label>Replace image<input type="file" name="image_file" accept="image/jpeg,image/png,image/webp"></label><label class="check"><input type="checkbox" name="featured" <?=$r['featured']?'checked':''?>> Featured</label><label class="check"><input type="checkbox" name="is_active" checked> Published</label><button class="btn primary small">Save</button></form></details><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="delete_photo"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger small" onclick="return confirm('Remove this photograph from the website?')">Remove</button></form></div></article><?php endforeach;?></div>
<?php elseif($page==='content'):?><div class="panel"><h3>Website wording</h3><p class="muted">Edit the text displayed on your public pages.</p><?php admin_form_start('save_content');$items=$pdo->query("SELECT * FROM website_content ORDER BY id")->fetchAll();foreach($items as $r){if(in_array($r['content_key'],['hero_image','about_image'],true))continue;textarea_field(ucwords(str_replace('_',' ',$r['content_key'])),'content['.$r['content_key'].']',$r['content_value']);}?><div class="form-grid"><label>Hero image<input type="file" name="hero_image_file" accept="image/jpeg,image/png,image/webp"></label><label>About section image<input type="file" name="about_image_file" accept="image/jpeg,image/png,image/webp"></label></div><button class="btn primary">Save website content</button></form></div>
<?php elseif($page==='theme'):?><div class="panel"><h3>Visual identity & theme</h3><p class="muted">Every setting below is applied to the public website after saving. The preview updates as you change values.</p><?php $theme=$pdo->query("SELECT * FROM theme_settings")->fetchAll(PDO::FETCH_KEY_PAIR);?><div id="theme-preview" class="theme-preview" style="--preview-header:<?=admin_h($theme['header_background']??'#1c5664')?>;--preview-page:<?=admin_h($theme['page_background']??'#f5fbfa')?>;--preview-card:<?=admin_h($theme['card_background']??'#fff')?>;--preview-heading:<?=admin_h($theme['heading_color']??'#123342')?>;--preview-text:<?=admin_h($theme['text_color']??'#344f59')?>;--preview-button:<?=admin_h($theme['button_background']??'#20b99a')?>;--preview-button-text:<?=admin_h($theme['button_text_color']??'#073b49')?>"><div class="theme-preview-header">Wave Photography <span>Menu</span></div><div class="theme-preview-body"><b>Every Picture Tells a Story</b><p>Your selected colours and typography preview</p><span class="theme-preview-button">Book a Session</span></div></div><?php admin_form_start('save_theme');?><div class="form-grid"><?php foreach($theme as $key=>$value):if(substr($key,-5)==='color'):?><label><?=admin_h(ucwords(str_replace('_',' ',$key)))?><input type="color" name="theme[<?=admin_h($key)?>]" value="<?=admin_h($value)?>" data-theme-key="<?=admin_h($key)?>"></label><?php elseif($key==='font_family'):?><label>Font Family<select name="theme[font_family]" data-theme-key="font_family"><?php foreach(['Inter','Arial','Georgia','Poppins','Roboto','Montserrat'] as $font):?><option value="<?=admin_h($font)?>" <?=$value===$font?'selected':''?>><?=admin_h($font)?></option><?php endforeach;?></select></label><?php elseif(in_array($key,['container_width','section_spacing','border_radius'],true)):?><label><?=admin_h(ucwords(str_replace('_',' ',$key)))?><input type="number" name="theme[<?=admin_h($key)?>]" value="<?=admin_h($value)?>" min="<?=$key==='container_width'?760:($key==='section_spacing'?32:0)?>" max="<?=$key==='container_width'?1800:($key==='section_spacing'?180:48)?>" data-theme-key="<?=admin_h($key)?>"></label><?php endif;endforeach;?></div><button class="btn primary">Save theme</button></form><?php admin_form_start('reset_theme');?><button class="btn danger" type="submit" onclick="return confirm('Restore default theme values?')">Reset to defaults</button></form></div>
<?php elseif($page==='navigation'):?><div class="panel" id="navigation-editor"><h3>Add / edit navigation link</h3><?php admin_form_start('save_navigation');?><input type="hidden" name="id" value=""><div class="form-grid"><?php field('Menu label','label');field('Destination URL','url');field('Display order','sort_order','0','number');?></div><label class="check"><input type="checkbox" name="is_active" checked> Visible</label><label class="check"><input type="checkbox" name="open_new_tab"> Open in new tab</label><button class="btn primary">Add menu item</button></form></div><div class="panel"><h3>Menu items</h3><?php foreach(rows("SELECT * FROM navigation_items ORDER BY sort_order,id") as $r):?><div class="manage-row"><div><b><?=admin_h($r['label'])?></b><small><?=admin_h($r['url'])?></small></div><span><?=$r['is_active']?'Visible':'Hidden'?> · Order <?=$r['sort_order']?></span><button type="button" class="btn small" data-edit-nav="<?=admin_h(json_encode($r))?>">Edit</button><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="delete_navigation"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger small" onclick="return confirm('Delete this menu item?')">Delete</button></form></div><?php endforeach;?></div>
<?php elseif($page==='settings'):?><div class="panel"><h3>Global website settings</h3><?php admin_form_start('save_settings');$settings=$pdo->query("SELECT * FROM site_settings ORDER BY setting_key")->fetchAll();?><div class="form-grid"><?php foreach($settings as $r):if(in_array($r['setting_key'],['logo','favicon'],true))continue;field(ucwords(str_replace('_',' ',$r['setting_key'])),'settings['.$r['setting_key'].']',$r['setting_value']);endforeach;?><label>Website logo (PNG/JPG/WebP)<input type="file" name="logo_file" accept="image/jpeg,image/png,image/webp"></label><label>Favicon image<input type="file" name="favicon_file" accept="image/jpeg,image/png,image/webp"></label></div><button class="btn primary">Save settings</button></form></div>
<?php elseif($page==='testimonials'):?><div class="panel" id="testimonial-editor"><h3>Add / edit customer testimonial</h3><?php admin_form_start('save_testimonial');?><input type="hidden" name="id" value=""><div class="form-grid"><?php field('Customer name','customer_name');field('Photography category','category');?></div><?php textarea_field('Review','review');?><label class="check"><input type="checkbox" name="is_active" checked> Publish</label><button class="btn primary">Save testimonial</button></form></div><div class="panel"><?php foreach(rows("SELECT * FROM testimonials ORDER BY sort_order,id") as $r):?><div class="manage-row"><div><b><?=admin_h($r['customer_name'])?></b><small><?=admin_h($r['category'])?></small></div><span><?=admin_h($r['review'])?></span><button type="button" class="btn small" data-edit-testimonial="<?=admin_h(json_encode($r))?>">Edit</button><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="delete_testimonial"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn danger small">Hide</button></form></div><?php endforeach;?></div>
<?php elseif($page==='bookings'):?><div class="panel"><h3>Customer enquiries</h3><?php foreach(rows("SELECT * FROM bookings ORDER BY created_at DESC LIMIT 200") as $r):?><div class="manage-row"><div><b><?=admin_h($r['customer_name'])?></b><small><?=admin_h($r['phone'])?> · <?=admin_h($r['email'])?></small></div><span><?=admin_h($r['event_type'])?> · <?=admin_h($r['event_date'])?><br><?=admin_h($r['message'])?></span><form method="post"><input type="hidden" name="csrf" value="<?=admin_h(admin_csrf())?>"><input type="hidden" name="action" value="booking_status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><option <?= $r['status']==='new'?'selected':''?>>new</option><option <?= $r['status']==='contacted'?'selected':''?>>contacted</option><option <?= $r['status']==='confirmed'?'selected':''?>>confirmed</option><option <?= $r['status']==='closed'?'selected':''?>>closed</option></select><button class="btn small primary">Update</button></form></div><?php endforeach;?></div>
<?php elseif($page==='account'):?><div class="panel"><h3>Change administrator password</h3><?php admin_form_start('change_password');?><div class="form-grid"><?php field('Current password','current_password','','password');field('New password (minimum 10 characters)','new_password','','password');?></div><button class="btn primary">Update password</button></form></div>
<?php elseif($page==='media'):?><div class="panel"><h3>Uploaded media library</h3><p class="muted">All images uploaded through the admin portal, including service covers, gallery photos, website logo and content images.</p><div class="photo-grid"><?php foreach(rows("SELECT * FROM media_library ORDER BY id DESC LIMIT 300") as $r):?><article class="photo-card"><img src="../<?=admin_h($r['file_path'])?>" alt="<?=admin_h($r['alt_text']??$r['original_name'])?>"><div><b><?=admin_h($r['original_name'])?></b><small><?=admin_h($r['mime_type'])?> · <?=number_format((int)$r['file_size']/1024)?> KB</small><small><?=admin_h($r['file_path'])?></small></div></article><?php endforeach;?></div></div>
<?php elseif($page==='activity'):?><div class="panel"><h3>Administrative activity</h3><?php foreach(rows("SELECT l.*,u.username FROM admin_activity_logs l LEFT JOIN admin_users u ON u.id=l.admin_id ORDER BY l.id DESC LIMIT 100") as $r):?><div class="activity-row"><b><?=admin_h($r['action'])?></b><span><?=admin_h($r['details'])?></span><time><?=admin_h($r['username'].' · '.$r['created_at'])?></time></div><?php endforeach;?></div><?php endif;?></div><footer class="admin-footer">Wave Photography Admin · Secure website management</footer></main></div><script>
(function(){
  document.querySelectorAll('input[type="color"][name^="theme["]').forEach(function(input){
    input.addEventListener('input',function(){
      var key=input.name.slice(6,-1).replace(/_/g,'-');
      document.documentElement.style.setProperty('--'+key,input.value);
    });
  });
  document.querySelectorAll('form').forEach(function(form){
    form.addEventListener('submit',function(){
      var button=form.querySelector('button[type="submit"],button:not([type])');
      if(button && !button.disabled){button.disabled=true;button.dataset.oldText=button.textContent;button.textContent='Saving…';}
    });
  });
  function editRows(selector,dataKey,formSelector,fields,after){
    document.querySelectorAll(selector).forEach(function(button){
      button.addEventListener('click',function(){
        var form=document.querySelector(formSelector);
        if(!form)return;
        var data;
        try{data=JSON.parse(button.dataset[dataKey]||'{}');}
        catch(error){return;}
        fields.forEach(function(name){var input=form.querySelector('[name="'+name+'"]');if(input)input.value=data[name] == null ? '' : data[name];});
        if(after)after(form,data);
        var panel=form.closest('.panel')||form;
        panel.scrollIntoView({behavior:'smooth',block:'start'});
      });
    });
  }
  editRows('[data-edit-section]','editSection','#section-editor form',['id','name','slug','category','description','sort_order','layout'],function(form,data){
    var image=form.querySelector('[name="existing_image"]');if(image)image.value=data.cover_image||'';
    var active=form.querySelector('[name="is_active"]');if(active)active.checked=!!Number(data.is_active);
  });
  editRows('[data-edit-service]','editService','#service-editor form',['id','name','slug','category','description','sort_order'],function(form,data){
    var image=form.querySelector('[name="image"]');if(image)image.value=data.image||'';
    var active=form.querySelector('[name="is_active"]');if(active)active.checked=!!Number(data.is_active);
    var inclusions=form.querySelector('[name="inclusions"]');if(inclusions){try{inclusions.value=JSON.parse(data.inclusions||'[]').join('\n');}catch(error){inclusions.value='';}}
  });
  editRows('[data-edit-nav]','editNav','#navigation-editor form',['id','label','url','sort_order'],function(form,data){
    ['open_new_tab','is_active'].forEach(function(name){var input=form.querySelector('[name="'+name+'"]');if(input)input.checked=!!Number(data[name]);});
  });
  editRows('[data-edit-testimonial]','editTestimonial','#testimonial-editor form',['id','customer_name','category','review','rating'],function(form,data){
    var active=form.querySelector('[name="is_active"]');if(active)active.checked=!!Number(data.is_active);
    var image=form.querySelector('[name="customer_image"]');if(image)image.value=data.customer_image||'';
  });
  var preview=document.getElementById('theme-preview');
  if(preview){
    var previewMap={header_background:'--preview-header',page_background:'--preview-page',card_background:'--preview-card',heading_color:'--preview-heading',text_color:'--preview-text',button_background:'--preview-button',button_text_color:'--preview-button-text'};
    document.querySelectorAll('[data-theme-key]').forEach(function(input){
      var update=function(){var key=input.dataset.themeKey;if(previewMap[key])preview.style.setProperty(previewMap[key],input.value);if(key==='font_family')preview.querySelector('.theme-preview-body b').style.fontFamily=input.value;};
      input.addEventListener('input',update);input.addEventListener('change',update);
    });
  }
  var menuButton=document.querySelector('.mobile-menu');
  if(menuButton)menuButton.addEventListener('click',function(){document.getElementById('sidebar')?.classList.toggle('show');});
})();
</script></body></html>
